version: "3.8"
services:
  app:
    build: .
    image: biocall-server/app
    ports:
      - 4001:4001 # the app uses port 4001
    volumes:
      - "./log:/var/log/biocall-server" # log files stored in /var/log/biocall-server in the container
                                        # ./log: directory on host machine to store log files